import{a as P,S as M,i as n}from"./assets/vendor-DirGshhi.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&d(l)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function d(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const q="https://pixabay.com/api/",E="56128915-3f9b657c3018140957932d29d",O=15;async function u(o,e){return(await P.get(q,{params:{key:E,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:O}})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),p=document.querySelector(".load-more"),$=new M(".gallery a",{captionsDelay:250,captionsData:"title"}),h=document.querySelector(".end-message");function g(){h.classList.remove("is-hidden")}function B(){h.classList.add("is-hidden")}function I(){f.innerHTML=""}function y(){m.classList.remove("is-hidden")}function L(){m.classList.add("is-hidden")}function b(){p.classList.remove("is-hidden")}function i(){p.classList.add("is-hidden")}function w(o){const e=o.map(r=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${r.largeImageURL}">
          <img 
            class="gallery-image" 
            src="${r.webformatURL}" 
            alt="${r.tags}" 
            title="${r.tags}" 
          />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b> ${r.likes}</p>
          <p class="info-item"><b>Views</b> ${r.views}</p>
          <p class="info-item"><b>Comments</b> ${r.comments}</p>
          <p class="info-item"><b>Downloads</b> ${r.downloads}</p>
        </div>
      </li>`).join("");f.insertAdjacentHTML("beforeend",e),$.refresh()}n.settings({timeout:1e4,resetOnHover:!0,icon:"material-icons",transitionIn:"flipInX",transitionOut:"flipOutX"});const S=document.querySelector(".form"),H=document.querySelector(".load-more");let c="",a=1;const v=15;S.addEventListener("submit",x);H.addEventListener("click",A);i();async function x(o){if(o.preventDefault(),c=o.currentTarget.elements["search-text"].value.trim(),a=1,I(),i(),B(),c===""){n.error({message:"Search cannot be empty!",position:"topLeft"});return}y();try{const e=await u(c,a);if(e.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topLeft"});return}w(e.hits);const r=Math.ceil(e.totalHits/v);a>=r?(i(),g(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topLeft"})):b()}catch{n.error({message:"Something went wrong. Please try again later.",position:"topLeft"})}finally{L(),S.reset()}}async function A(){a+=1,i(),y();try{const o=await u(c,a);w(o.hits),R();const e=Math.ceil(o.totalHits/v);a>=e?(i(),g(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topLeft"})):b()}catch{n.error({message:"Something went wrong. Please try again later.",position:"topLeft"})}finally{L()}}function R(){const o=document.querySelector(".gallery-item");if(!o)return;const e=o.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
